In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('covid_19_indonesia_time_series_all.csv')

In [3]:
df.head()

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,New Deaths per Million,Total Deaths per Million,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths,Name,Item,Kind,Hidden
0,1/8/2020,ID-JI,Jawa Timur,9,3,1,5,9,5,10,...,0.07,0.12,55.56%,111.11%,NaN,NaN,NaN,NaN,NaN,NaN
1,1/9/2020,ID-JI,Jawa Timur,0,1,23,-24,9,6,33,...,0.02,0.15,66.67%,366.67%,0.0,0.33,NaN,NaN,NaN,NaN
2,1/10/2020,ID-JI,Jawa Timur,0,1,14,-15,9,7,47,...,0.02,0.17,77.78%,522.22%,1.0,1.00,NaN,NaN,NaN,NaN
3,1/11/2020,ID-JI,Jawa Timur,0,3,8,-11,9,10,55,...,0.07,0.25,111.11%,611.11%,1.0,3.00,NaN,NaN,NaN,NaN
4,1/12/2020,ID-JI,Jawa Timur,0,3,1,-4,9,13,56,...,0.07,0.32,144.44%,622.22%,1.0,1.00,NaN,NaN,NaN,NaN

In [4]:
df.shape

(16283, 41)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16283 entries, 0 to 16282
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         16283 non-null  object
 1   Location ISO Code            16283 non-null  object
 2   Location                     16283 non-null  object
 3   New Cases                    16283 non-null  int64
 4   New Deaths                   16283 non-null  int64
 5   New Recovered                16283 non-null  int64
 6   New Active Cases             16283 non-null  int64
 7   Total Cases                  16283 non-null  int64
 8   Total Deaths                 16283 non-null  int64
 9   Total Recovered              16283 non-null  int64
 10  Total Active Cases           16283 non-null  int64
 11  Location Level               16283 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     15788 non-null  object
 14  Country                      16283 non-null  object
 15  Continent                    16283 non-null  object
 16  Island                       15788 non-null  object
 17  Time Zone                    15788 non-null  object
 18  Special Status               2393 non-null   object
 19  Total Regencies              16283 non-null  int64
 20  Total Cities                 15814 non-null  float64
 21  Total Districts              16283 non-null  int64
 22  Total Urban Villages         15812 non-null  float64
 23  Total Rural Villages         15787 non-null  float64
 24  Area (km2)                   16283 non-null  int64
 25  Population                   16283 non-null  int64
 26  Population Density           16283 non-null  float64
 27  Longitude                    16283 non-null  float64
 28  Latitude                     16283 non-null  float64
 29  New Cases per Million        16283 non-null  float64
 30  Total Cases per Million      16283 non-null  float64
 31  New Deaths per Million       16283 non-null  float64
 32  Total Deaths per Million     16283 non-null  float64
 33  Case Fatality Rate           16283 non-null  object
 34  Case Recovered Rate          16283 non-null  object
 35  Growth Factor of New Cases   15298 non-null  float64
 36  Growth Factor of New Deaths  14344 non-null  float64
 37  Name                         0 non-null      float64
 38  Item                         0 non-null      float64
 39  Kind                         0 non-null      float64
 40  Hidden                       0 non-null      float64
dtypes: float64(17), int64(12), object(12)
memory usage: 5.1+ MB

In [6]:
df_copy = df

In [ ]:
df_copy.drop('Name',)